# Generated by Django 5.1.1 on 2024-09-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_hospital_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='district',
            field=models.CharField(choices=[('Woldia', 'Woldia'), ('Dessie', 'Dessie'), ('Alemata', 'Alemata'), ('Kobo', 'Kobo'), ('Gashena', 'Gashena'), ('Gonder', 'Gonder'), ('Kombolcha', 'Kombolcha'), ('Sanka', 'Sanka'), ('Wuchale', 'Wuchale'), ('Mersa', 'Mersa'), ('sekota', 'sekota'), ('Gobye', 'Gobye'), ('Sirinka', 'Sirinka'), ('Wurgesa', 'Wurgesa')], max_length=100),
        ),
    ]
